var a;
var b;
var c;
var d;
var e = [1, 3, 4];
var f = [true, 1, 2, 3, 4, false];
var colorRed = 0;
var colorGreen = 1;
var colorBlue = 2;
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Purple"] = 3] = "Purple";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
// let bgColor=colorRed;
var bgColor = Color.Red;
console.log("Red", Color.Red);
console.log("Purple", Color.Purple);
